// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgtZfFHUoUbji-TvozYgFkCoB91Dxt9Jw',
    appId: '1:386439325454:web:c71a56d8718b45f245995f',
    messagingSenderId: '386439325454',
    projectId: 'service-plus-dfa00',
    authDomain: 'service-plus-dfa00.firebaseapp.com',
    storageBucket: 'service-plus-dfa00.appspot.com',
    measurementId: 'G-SMCJFW9J8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnQNuGHHz4eDtO7Lj4kTyM70pCxWk_L5M',
    appId: '1:386439325454:android:e23afb4af2e4eb6745995f',
    messagingSenderId: '386439325454',
    projectId: 'service-plus-dfa00',
    storageBucket: 'service-plus-dfa00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFIh4q6sgD30u7wfcOTzUmDnzi87YSlvs',
    appId: '1:386439325454:ios:a1ac47119cdc6a1245995f',
    messagingSenderId: '386439325454',
    projectId: 'service-plus-dfa00',
    storageBucket: 'service-plus-dfa00.appspot.com',
    iosBundleId: 'com.example.servicePlusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFIh4q6sgD30u7wfcOTzUmDnzi87YSlvs',
    appId: '1:386439325454:ios:a1ac47119cdc6a1245995f',
    messagingSenderId: '386439325454',
    projectId: 'service-plus-dfa00',
    storageBucket: 'service-plus-dfa00.appspot.com',
    iosBundleId: 'com.example.servicePlusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgtZfFHUoUbji-TvozYgFkCoB91Dxt9Jw',
    appId: '1:386439325454:web:64a395191e180f8645995f',
    messagingSenderId: '386439325454',
    projectId: 'service-plus-dfa00',
    authDomain: 'service-plus-dfa00.firebaseapp.com',
    storageBucket: 'service-plus-dfa00.appspot.com',
    measurementId: 'G-51T0GZ02BM',
  );
}
